import { ArrowLeft, ArrowRight, ArrowUpRight, BookOpen, CalendarDays, Tag } from "lucide-react";
import { useEffect, useState } from "react";
import { Link } from "wouter";
import { trpc } from "@/lib/trpc";
import { useRealtime } from "@/hooks/useRealtime";
import ScrollDepthBackground from "@/components/ScrollDepthBackground";
import NewsletterSignup from "@/components/NewsletterSignup";
import SiteFooter from "@/components/SiteFooter";

export default function Blog() {
  useRealtime("storefront");
  const [page, setPage] = useState(1);
  const posts = trpc.blog.list.useQuery({ page, pageSize: 6 });
  useEffect(() => { document.title = "The DevMarket Blog — Practical Ideas for Builders"; }, []);
  const data = posts.data;

  return <div className="liquid-page min-h-screen overflow-hidden bg-[#eef8fa] text-[#172039]"><ScrollDepthBackground />
    <header className="site-header"><div className="site-nav-pill mx-auto flex max-w-[1080px] items-center justify-between px-4 py-3 lg:px-5"><Link href="/" className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#172039] text-[#c7f76d]"><BookOpen size={18} /></span><span className="font-display text-xl font-bold tracking-[-.05em]">dev<span className="text-[#13b8b0]">market</span></span></Link><Link href="/" className="inline-flex items-center gap-2 text-sm font-semibold text-[#53617d] transition hover:text-[#13b8b0]"><ArrowLeft size={15} /> Back to marketplace</Link></div></header>
    <main className="relative z-10 mx-auto max-w-[1280px] px-5 pb-24 pt-32 lg:px-8 lg:pt-40">
      <section className="max-w-3xl"><p className="font-mono text-[11px] uppercase tracking-[.22em] text-[#13b8b0]">The DevMarket blog</p><h1 className="mt-5 font-display text-6xl font-semibold leading-[.88] tracking-[-.09em] md:text-8xl">Ideas for<br /><span className="text-[#13b8b0]">shipping well.</span></h1><p className="mt-8 max-w-2xl text-xl leading-8 text-[#53617d]">Practical notes on AI-assisted development, digital products, and the small decisions that turn a rough idea into useful work.</p></section>
      <div className="mt-16 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{posts.isLoading ? <div className="col-span-full rounded-2xl border border-dashed border-[#b9d6db] p-14 text-center text-[#53617d]">Loading the blog…</div> : data?.posts.length ? data.posts.map(post => <Link href={`/blog/${post.slug}`} key={post.id}><article className="group h-full overflow-hidden rounded-[1.75rem] border border-[#d7e8eb] bg-[#f8ffff] transition duration-200 hover:-translate-y-1 hover:border-[#13b8b0] hover:shadow-[0_18px_45px_rgba(23,32,57,.1)]"><div className="relative flex aspect-[1.55/1] items-end overflow-hidden bg-gradient-to-br from-[#d9f8f6] via-[#eef8fa] to-[#ded9ff] p-5">{post.coverImageUrl ? <img src={post.coverImageUrl} alt="" className="absolute inset-0 h-full w-full object-cover transition duration-500 group-hover:scale-105" /> : <div className="absolute inset-0 opacity-60" aria-hidden="true"><div className="absolute -left-10 -top-16 h-48 w-48 rounded-full bg-[#13b8b0]/25" /><div className="absolute -bottom-20 -right-8 h-56 w-56 rounded-full bg-[#7658f5]/20" /></div>}<span className="relative z-10 rounded-full bg-[#f8ffffe8] px-3 py-1.5 font-mono text-[10px] uppercase tracking-[.16em] text-[#172039]">{post.category}</span></div><div className="flex h-[calc(100%-13rem)] flex-col p-6"><div className="flex items-center gap-3 text-[10px] uppercase tracking-[.12em] text-[#71809f]"><CalendarDays size={13} className="text-[#13b8b0]" />{new Date(post.publishedAt ?? post.createdAt).toLocaleDateString("en-IN", { day: "numeric", month: "short", year: "numeric" })}<span>·</span><span>{post.authorName}</span></div><h2 className="mt-5 font-display text-2xl font-semibold leading-[.98] tracking-[-.05em] transition group-hover:text-[#13b8b0]">{post.title}</h2><p className="mt-3 flex-1 leading-7 text-[#53617d]">{post.excerpt}</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-semibold">Read article <ArrowUpRight size={15} /></span><div className="mt-5 flex flex-wrap gap-2">{((post.tags as string[] | null) ?? []).slice(0, 3).map(tag => <span key={tag} className="inline-flex items-center gap-1 rounded-full bg-[#e9f7f6] px-2.5 py-1 text-[10px] font-semibold text-[#53617d]"><Tag size={11} />{tag}</span>)}</div></div></article></Link>) : <div className="col-span-full rounded-2xl border border-dashed border-[#b9d6db] p-14 text-center"><BookOpen className="mx-auto text-[#13b8b0]" size={30} /><h2 className="mt-4 font-display text-2xl font-semibold">The blog is getting ready.</h2><p className="mt-2 text-[#53617d]">New practical articles will appear here soon.</p></div>}</div>
      {data && data.totalPages > 1 && <nav aria-label="Blog pagination" className="mt-10 flex items-center justify-center gap-3"><button type="button" disabled={page === 1} onClick={() => setPage(current => Math.max(1, current - 1))} className="inline-flex items-center gap-2 rounded-full border border-[#d7e8eb] bg-[#f8ffff] px-4 py-2.5 text-sm font-semibold disabled:cursor-not-allowed disabled:opacity-40"><ArrowLeft size={15} /> Previous</button><span className="font-mono text-[10px] uppercase tracking-[.16em] text-[#71809f]">Page {data.page} of {data.totalPages}</span><button type="button" disabled={page >= data.totalPages} onClick={() => setPage(current => Math.min(data.totalPages, current + 1))} className="inline-flex items-center gap-2 rounded-full bg-[#172039] px-4 py-2.5 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-40">Next <ArrowRight size={15} /></button></nav>}
      <div className="mt-16"><NewsletterSignup /></div>
    </main>
    <SiteFooter />
  </div>;
}
