import { ArrowLeft, ArrowUpRight, Bot, Code2, Globe2, Layers3, Mail, Sparkles, Workflow } from "lucide-react";
import { Link } from "wouter";

const skills = [
  { icon: <Workflow size={20} />, title: "Automated works", copy: "Designing repeatable workflows that connect tools, APIs, agents, and people so useful work keeps moving with less manual effort." },
  { icon: <Bot size={20} />, title: "AI & LLM systems", copy: "Working with modern AI models to turn natural language into practical research, content, coding, and product experiences." },
  { icon: <Globe2 size={20} />, title: "AI-assisted web development", copy: "Building websites with AI generation while keeping the experience understandable, controllable, accessible, and legitimate for users." },
  { icon: <Layers3 size={20} />, title: "AI-assisted app development", copy: "Exploring mobile and full-stack applications where AI speeds up creation without replacing product thinking, privacy, or user consent." },
];

const principles = [
  ["01", "Useful over flashy", "Technology should reduce friction and help a real person complete something meaningful."],
  ["02", "AI with legitimacy", "AI-generated experiences should be transparent, safe, and designed around the user—not hidden behind hype."],
  ["03", "Learn by shipping", "Small experiments, working prototypes, and honest iteration create deeper understanding than theory alone."],
  ["04", "Keep the human in control", "Automation is most valuable when people can inspect it, guide it, and make the final decision."],
];

export default function Developer() {
  return <div className="liquid-page min-h-screen overflow-hidden bg-[#eef8fa] text-[#172039]">
    <header className="relative z-10 border-b border-white/80 bg-white/65">
      <div className="mx-auto flex max-w-[1280px] items-center justify-between px-5 py-5 lg:px-8">
        <Link href="/" className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#172039] text-[#c7f76d]"><Code2 size={18} /></span><span className="font-display text-xl font-bold tracking-[-.05em]">dev<span className="text-[#13b8b0]">market</span></span></Link>
        <Link href="/" className="inline-flex items-center gap-2 text-sm font-semibold text-[#53617d] transition hover:text-[#13b8b0]"><ArrowLeft size={15} /> Back to marketplace</Link>
      </div>
    </header>

    <main>
      <section className="relative mx-auto max-w-[1280px] px-5 pb-20 pt-14 lg:px-8 lg:pb-28 lg:pt-20">
        <div className="grid items-center gap-12 lg:grid-cols-[.9fr_1.1fr]">
          <div className="order-2 lg:order-1">
            <p className="font-mono text-[11px] uppercase tracking-[.22em] text-[#13b8b0]">Developer profile / 001</p>
            <h1 className="mt-5 max-w-2xl font-display text-[clamp(3.6rem,8vw,7.8rem)] font-semibold leading-[.84] tracking-[-.1em]">Nitin<br /><span className="text-[#13b8b0]">Sharma.</span></h1>
            <p className="mt-8 max-w-xl text-xl leading-8 text-[#53617d]">A 16-year-old computer science engineering student exploring the space where automation, AI, and thoughtful product design meet.</p>
            <div className="mt-9 flex flex-wrap gap-3"><a href="#work" className="btn inline-flex items-center rounded-full bg-[#172039] px-6 py-3.5 text-sm font-semibold text-white hover:bg-[#13b8b0]">Explore capabilities <ArrowUpRight className="ml-2" size={16} /></a><a href="#story" className="btn inline-flex items-center rounded-full border border-[#b9d6db] bg-white/45 px-6 py-3.5 text-sm font-semibold text-[#172039]">Read the story</a></div>
            <div className="mt-12 grid max-w-lg grid-cols-3 gap-3"><div className="glass rounded-2xl p-4"><p className="font-display text-2xl font-semibold">16</p><p className="mt-1 font-mono text-[9px] uppercase tracking-[.12em] text-[#71809f]">Years old</p></div><div className="glass rounded-2xl p-4"><p className="font-display text-2xl font-semibold">CS</p><p className="mt-1 font-mono text-[9px] uppercase tracking-[.12em] text-[#71809f]">Engineering</p></div><div className="glass rounded-2xl p-4"><p className="font-display text-2xl font-semibold">∞</p><p className="mt-1 font-mono text-[9px] uppercase tracking-[.12em] text-[#71809f]">Curiosity</p></div></div>
          </div>
          <div className="order-1 relative mx-auto w-full max-w-[560px] lg:order-2 lg:justify-self-end"><div className="liquid-blob liquid-blob-a -right-7 top-8" /><div className="relative rotate-2 overflow-hidden rounded-[2.5rem] border-[10px] border-[#172039] bg-[#172039] shadow-[0_28px_70px_rgba(23,32,57,.22)]"><img src="/manus-storage/nitin-sharma-developer_2854d7c9.jpg" alt="Portrait of Nitin Sharma" decoding="async" fetchPriority="high" className="aspect-square w-full object-cover" /><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-[#172039]/85 via-[#172039]/20 to-transparent p-7 pt-24 text-white"><div className="flex items-end justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[.18em] text-[#c7f76d]">Builder in progress</p><p className="mt-2 font-display text-2xl font-semibold">Learning. Building. Sharing.</p></div><Sparkles className="text-[#c7f76d]" size={26} /></div></div></div><div className="absolute -bottom-7 -left-7 rounded-full border border-white/90 bg-white/80 px-5 py-4 text-center font-mono text-[10px] uppercase leading-4 tracking-[.1em] shadow-lg">Made with<br />curiosity</div></div>
        </div>
      </section>

      <section id="story" className="border-y border-white/80 bg-white/38 py-20"><div className="mx-auto grid max-w-[1280px] gap-12 px-5 lg:grid-cols-[.72fr_1.28fr] lg:px-8"><div><p className="font-mono text-[11px] uppercase tracking-[.2em] text-[#13b8b0]">The story so far</p><h2 className="mt-4 max-w-sm font-display text-4xl font-semibold leading-[.92] tracking-[-.07em] md:text-6xl">A student building beyond the syllabus.</h2></div><div className="max-w-2xl space-y-6 text-lg leading-8 text-[#53617d]"><p>My name is <strong className="text-[#172039]">Nitin Sharma</strong>. I am 16 years old and currently studying Computer Science Engineering at <strong className="text-[#172039]">Government Polytechnic Sergarh, Kaithal</strong>.</p><p>I enjoy taking a rough idea and turning it into something people can actually use. That can mean automating a repetitive workflow, experimenting with an AI assistant, creating a website, or shaping an app from a blank screen into a clear experience.</p><p>My focus is not simply to generate more software. It is to learn how technology can be made useful, responsible, and understandable—especially when AI is part of the process.</p></div></div></section>

      <section id="work" className="mx-auto max-w-[1280px] px-5 py-20 lg:px-8"><div className="mb-10 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="font-mono text-[11px] uppercase tracking-[.2em] text-[#13b8b0]">Core capabilities</p><h2 className="mt-3 font-display text-4xl font-semibold tracking-[-.07em] md:text-5xl">What I’m learning to build.</h2></div><p className="max-w-sm text-sm leading-6 text-[#53617d]">A growing toolkit shaped by hands-on experiments, responsible AI use, and the desire to make digital work feel simpler.</p></div><div className="grid gap-4 md:grid-cols-2">{skills.map((skill, index) => <article key={skill.title} className="glass group rounded-[1.75rem] p-7 transition duration-200 hover:-translate-y-1"><div className="flex items-start justify-between"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[#d9f8f6] text-[#13b8b0]">{skill.icon}</span><span className="font-mono text-xs text-[#71809f]">0{index + 1}</span></div><h3 className="mt-12 font-display text-2xl font-semibold tracking-[-.05em]">{skill.title}</h3><p className="mt-3 max-w-md leading-7 text-[#53617d]">{skill.copy}</p></article>)}</div></section>

      <section className="mx-5 mb-20 overflow-hidden rounded-[2rem] bg-[#172039] py-20 text-white lg:mx-auto lg:max-w-[1232px]"><div className="mx-auto max-w-5xl px-7 lg:px-14"><div className="grid gap-12 lg:grid-cols-[.9fr_1.1fr]"><div><p className="font-mono text-[11px] uppercase tracking-[.2em] text-[#c7f76d]">How I approach AI</p><h2 className="mt-4 font-display text-4xl font-semibold leading-[.9] tracking-[-.07em] md:text-6xl">Fast tools.<br /><span className="text-[#13b8b0]">Human judgment.</span></h2></div><div className="space-y-6 text-lg leading-8 text-white/70"><p>AI can help me move from a question to a prototype quickly. It can help with research, structure, debugging, design directions, and repetitive work.</p><p>But the goal is legitimate value for users. I care about clear outcomes, truthful communication, privacy-aware decisions, accessible interfaces, and keeping people in control of the final result.</p><div className="flex flex-wrap gap-2 pt-2"><span className="rounded-full border border-white/20 px-4 py-2 font-mono text-[10px] uppercase tracking-[.14em]">Transparent</span><span className="rounded-full border border-white/20 px-4 py-2 font-mono text-[10px] uppercase tracking-[.14em]">Useful</span><span className="rounded-full border border-white/20 px-4 py-2 font-mono text-[10px] uppercase tracking-[.14em]">User-first</span></div></div></div></div></section>

      <section className="mx-auto max-w-[1280px] px-5 pb-20 lg:px-8"><div className="mb-10"><p className="font-mono text-[11px] uppercase tracking-[.2em] text-[#13b8b0]">Working principles</p><h2 className="mt-3 font-display text-4xl font-semibold tracking-[-.07em] md:text-5xl">The standard I’m aiming for.</h2></div><div className="grid gap-3 md:grid-cols-2">{principles.map(([number, title, copy]) => <div key={number} className="glass flex gap-5 rounded-2xl p-6"><span className="font-mono text-sm text-[#13b8b0]">{number}</span><div><h3 className="font-display text-xl font-semibold">{title}</h3><p className="mt-2 leading-6 text-[#53617d]">{copy}</p></div></div>)}</div></section>

      <section className="border-t border-white/80 bg-white/38 py-16"><div className="mx-auto flex max-w-[1280px] flex-col items-start justify-between gap-7 px-5 md:flex-row md:items-end lg:px-8"><div><p className="font-mono text-[11px] uppercase tracking-[.2em] text-[#13b8b0]">Currently exploring</p><h2 className="mt-3 max-w-xl font-display text-4xl font-semibold leading-[.95] tracking-[-.07em] md:text-5xl">Automation systems, AI-native products, and better ways to learn by building.</h2></div><a href="mailto:nitin.sharma@example.com" className="btn inline-flex items-center rounded-full bg-[#13b8b0] px-6 py-3.5 text-sm font-semibold text-white hover:bg-[#172039]"><Mail className="mr-2" size={16} /> Start a conversation</a></div></section>
    </main>

    <footer className="border-t border-white/80 px-5 py-8 lg:px-8"><div className="mx-auto flex max-w-[1280px] flex-col justify-between gap-4 text-sm text-[#53617d] md:flex-row"><span className="font-display font-semibold text-[#172039]">Nitin Sharma / Developer</span><span>Building with curiosity and responsibility.</span><span className="font-mono text-[10px] uppercase tracking-[.14em]">© 2026</span></div></footer>
  </div>;
}
