import { ArrowLeft, Mail, ShieldCheck } from "lucide-react";
import { Link, useLocation } from "wouter";
import ScrollDepthBackground from "@/components/ScrollDepthBackground";
import { useEffect } from "react";
import SiteFooter from "@/components/SiteFooter";

const pages = {
  "/about": { eyebrow: "About DevMarket", title: "A focused marketplace for people who build.", intro: "DevMarket helps builders discover production-ready source code, AI prompt systems, and complete digital projects without wasting time on vague promises.", sections: [["Why it exists", "Good digital work is often hidden behind scattered repositories, half-finished tutorials, and unclear product pages. DevMarket brings focused, usable resources into one clear marketplace."], ["What we value", "Each listing should communicate what it does, who it is for, what is included, and how the buyer can use it. Clear expectations make digital purchases better for everyone."], ["Built by a learner", "DevMarket is being shaped by Nitin Sharma, a Computer Science Engineering student exploring automation, AI, web development, and app development with a practical, user-first mindset."]] },
  "/privacy": { eyebrow: "Privacy policy", title: "Simple, respectful data practices.", intro: "This page explains the information DevMarket may process when you browse, sign in, purchase, or contact us.", sections: [["Information we use", "Account details supplied through authentication, order information needed to fulfil a purchase, payment references supplied by the payment provider, and support messages you choose to send."], ["How information is used", "We use information to authenticate users, process and verify orders, provide purchased downloads, prevent abuse, respond to support requests, and improve the marketplace experience."], ["Payments and security", "Payment credentials are handled by the configured payment provider. DevMarket does not intentionally store full card details. Access to purchased files is checked against the buyer’s delivered order."], ["Your choices", "You can request clarification about your account information, ask about retention, or contact the team about a privacy concern using the contact page."]] },
  "/terms": { eyebrow: "Terms of use", title: "Clear expectations for a digital marketplace.", intro: "By using DevMarket, you agree to use the marketplace lawfully and respect the rights of creators, buyers, and other users.", sections: [["Digital products", "Product pages describe the intended contents and use cases. Buyers receive access only after successful payment verification or manual approval. Do not redistribute purchased files unless the product license explicitly allows it."], ["Accounts", "Keep account access secure and provide accurate information when completing a purchase. Do not attempt to bypass payment, delivery, or access controls."], ["Creator rights", "Creators remain responsible for the originality, licensing, and legality of the products they publish. Report suspected infringement or unsafe content through the contact page."], ["Changes", "Marketplace features, product availability, and these terms may change as the project develops. Material changes should be communicated clearly on the relevant page."]] },
  "/contact": { eyebrow: "Contact", title: "Have a question about a product or order?", intro: "Send a clear message and include the order number when your question is related to a purchase. We aim to respond with useful, specific guidance.", sections: [["Order support", "For payment verification, rejected proofs, or download access, include your order number and the email used to sign in. Never send passwords or payment card numbers."], ["Product questions", "Tell us which product you are considering and what you are trying to build. Specific context helps us point you toward the right resource."], ["Creator and partnership enquiries", "If you have a product, workflow, or collaboration idea, explain the audience, the value, and what you would like to contribute."]] }
} as const;

type PageKey = keyof typeof pages;

export default function InfoPage() {
  const [location] = useLocation();
  const page = pages[(location in pages ? location : "/about") as PageKey];
  useEffect(() => { document.title = `${page.eyebrow} | DevMarket`; }, [page.eyebrow]);
  return <div className="liquid-page min-h-screen bg-[#eef8fa] text-[#172039]"><ScrollDepthBackground /><header className="site-header"><div className="site-nav-pill mx-auto flex max-w-[1080px] items-center justify-between px-4 py-3 lg:px-5"><Link href="/" className="font-display text-xl font-bold tracking-[-.05em]">dev<span className="text-[#13b8b0]">market</span></Link><Link href="/" className="inline-flex items-center gap-2 text-sm font-semibold text-[#53617d]"><ArrowLeft size={15} /> Back to marketplace</Link></div></header><main className="mx-auto max-w-[1100px] px-5 pb-16 pt-32 lg:px-8 lg:pb-24 lg:pt-40"><p className="font-mono text-[11px] uppercase tracking-[.2em] text-[#13b8b0]">{page.eyebrow}</p><h1 className="mt-5 max-w-3xl font-display text-5xl font-semibold leading-[.9] tracking-[-.08em] md:text-7xl">{page.title}</h1><p className="mt-8 max-w-2xl text-xl leading-8 text-[#53617d]">{page.intro}</p><div className="mt-14 grid gap-4 md:grid-cols-2">{page.sections.map(([title, copy]) => <section key={title} className="glass rounded-[1.75rem] p-7"><ShieldCheck className="text-[#13b8b0]" size={20} /><h2 className="mt-8 font-display text-2xl font-semibold tracking-[-.05em]">{title}</h2><p className="mt-3 leading-7 text-[#53617d]">{copy}</p></section>)}</div><a href="mailto:nitin.sharma@example.com" className="btn mt-12 inline-flex items-center rounded-full bg-[#13b8b0] px-6 py-3.5 text-sm font-semibold text-white"><Mail className="mr-2" size={16} /> Contact the team</a></main><SiteFooter /></div>;
}
