import { Check, Edit3, FileText, Globe2, Plus, Trash2, X } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

type Draft = { title: string; slug: string; excerpt: string; content: string; coverImageUrl: string; category: string; tags: string; authorName: string; status: "DRAFT" | "PUBLISHED" };
const emptyDraft: Draft = { title: "", slug: "", excerpt: "", content: "", coverImageUrl: "", category: "Building with AI", tags: "", authorName: "Nitin Sharma", status: "DRAFT" };

export default function BlogAdminPanel() {
  const posts = trpc.admin.blogs.useQuery();
  const [draft, setDraft] = useState<Draft>(emptyDraft);
  const [editingId, setEditingId] = useState<number | null>(null);
  const [open, setOpen] = useState(false);
  const create = trpc.admin.createBlog.useMutation({ onSuccess: () => { void posts.refetch(); reset(); toast.success("Article saved"); } });
  const update = trpc.admin.updateBlog.useMutation({ onSuccess: () => { void posts.refetch(); reset(); toast.success("Article updated"); } });
  const remove = trpc.admin.deleteBlog.useMutation({ onSuccess: () => { void posts.refetch(); toast.success("Article deleted"); } });
  const set = (key: keyof Draft, value: string) => setDraft(current => ({ ...current, [key]: value }));
  function reset() { setDraft(emptyDraft); setEditingId(null); setOpen(false); }
  function edit(post: NonNullable<typeof posts.data>[number]) { setDraft({ title: post.title, slug: post.slug, excerpt: post.excerpt, content: post.content, coverImageUrl: post.coverImageUrl ?? "", category: post.category, tags: ((post.tags as string[] | null) ?? []).join(", "), authorName: post.authorName, status: post.status }); setEditingId(post.id); setOpen(true); }
  function submit(event: React.FormEvent) { event.preventDefault(); const input = { ...draft, coverImageUrl: draft.coverImageUrl || null, tags: draft.tags.split(",").map(tag => tag.trim()).filter(Boolean) }; if (editingId) update.mutate({ ...input, id: editingId }); else create.mutate(input); }
  return <section className="mt-9 rounded-2xl border border-[#d7e8eb] bg-[#f8ffff] p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="font-mono text-[10px] uppercase tracking-[.16em] text-[#71809f]">Editorial workspace</p><h2 className="mt-2 font-display text-2xl font-semibold">Blog posts</h2><p className="mt-2 max-w-xl text-sm leading-6 text-[#53617d]">Publish useful, original articles for builders. Drafts stay private until you choose Published.</p></div><button onClick={() => { setDraft(emptyDraft); setEditingId(null); setOpen(true); }} className="btn inline-flex items-center rounded-full bg-[#172039] px-4 py-2.5 text-sm font-semibold text-white"><Plus size={16} className="mr-2" /> New article</button></div>
    {open && <form onSubmit={submit} className="mt-7 grid gap-3 rounded-2xl bg-[#e9f7f6] p-5 md:grid-cols-2"><div className="flex items-center justify-between md:col-span-2"><p className="font-semibold">{editingId ? "Edit article" : "Write an article"}</p><button type="button" onClick={reset} aria-label="Close editor"><X size={18} /></button></div><input required placeholder="Title" value={draft.title} onChange={e => set("title", e.target.value)} className="rounded-xl border border-[#d7e8eb] bg-[#f8ffff] px-4 py-3 text-sm outline-none" /><input required placeholder="slug-like-this" value={draft.slug} onChange={e => set("slug", e.target.value.toLowerCase().replace(/\s+/g, "-"))} className="rounded-xl border border-[#d7e8eb] bg-[#f8ffff] px-4 py-3 text-sm outline-none" /><input required placeholder="Category" value={draft.category} onChange={e => set("category", e.target.value)} className="rounded-xl border border-[#d7e8eb] bg-[#f8ffff] px-4 py-3 text-sm outline-none" /><input required placeholder="Author name" value={draft.authorName} onChange={e => set("authorName", e.target.value)} className="rounded-xl border border-[#d7e8eb] bg-[#f8ffff] px-4 py-3 text-sm outline-none" /><input placeholder="Cover image URL (optional)" value={draft.coverImageUrl} onChange={e => set("coverImageUrl", e.target.value)} className="rounded-xl border border-[#d7e8eb] bg-[#f8ffff] px-4 py-3 text-sm outline-none md:col-span-2" /><input required placeholder="Tags, comma separated" value={draft.tags} onChange={e => set("tags", e.target.value)} className="rounded-xl border border-[#d7e8eb] bg-[#f8ffff] px-4 py-3 text-sm outline-none md:col-span-2" /><textarea required minLength={20} placeholder="Short excerpt for cards and SEO" value={draft.excerpt} onChange={e => set("excerpt", e.target.value)} className="min-h-24 rounded-xl border border-[#d7e8eb] bg-[#f8ffff] px-4 py-3 text-sm outline-none md:col-span-2" /><textarea required minLength={80} placeholder="Article content in Markdown" value={draft.content} onChange={e => set("content", e.target.value)} className="min-h-56 rounded-xl border border-[#d7e8eb] bg-[#f8ffff] px-4 py-3 text-sm leading-6 outline-none md:col-span-2" /><select value={draft.status} onChange={e => set("status", e.target.value)} className="rounded-xl border border-[#d7e8eb] bg-[#f8ffff] px-4 py-3 text-sm outline-none"><option value="DRAFT">Save as draft</option><option value="PUBLISHED">Publish now</option></select><button type="submit" disabled={create.isPending || update.isPending} className="rounded-full bg-[#13b8b0] px-5 py-3 text-sm font-semibold text-white">{create.isPending || update.isPending ? "Saving…" : editingId ? "Update article" : "Save article"}</button></form>}
    <div className="mt-7 space-y-3">{posts.isLoading ? <p className="py-8 text-center text-sm text-[#53617d]">Loading posts…</p> : posts.data?.length ? posts.data.map(post => <article key={post.id} className="flex flex-col gap-4 rounded-2xl border border-[#d7e8eb] p-4 md:flex-row md:items-center"><div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-xl bg-[#e9f7f6] text-[#13b8b0]">{post.status === "PUBLISHED" ? <Globe2 size={20} /> : <FileText size={20} />}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-display text-lg font-semibold">{post.title}</h3><span className={`rounded-full px-2.5 py-1 text-[10px] font-semibold uppercase ${post.status === "PUBLISHED" ? "bg-[#c7f76d] text-[#172039]" : "bg-[#fff4c6] text-[#8a6500]"}`}>{post.status}</span></div><p className="mt-1 text-sm text-[#53617d]">{post.category} · {post.authorName} · {post.slug}</p></div><div className="flex items-center gap-2"><button onClick={() => edit(post)} className="inline-flex items-center rounded-full border border-[#d7e8eb] px-3 py-2 text-sm font-semibold hover:bg-[#e9f7f6]"><Edit3 size={15} className="mr-1.5" /> Edit</button><button onClick={() => { if (window.confirm("Delete this article?")) remove.mutate({ id: post.id }); }} className="inline-flex items-center rounded-full bg-[#ffe0d7] px-3 py-2 text-sm font-semibold text-[#a33e23]" aria-label={`Delete ${post.title}`}><Trash2 size={15} /></button></div></article>) : <div className="rounded-2xl border border-dashed border-[#b9d6db] p-12 text-center text-[#53617d]">No blog posts yet. Start with an article for your future audience.</div>}</div>
  </section>;
}
