import { ArrowRight, Mail, CheckCircle2 } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

export default function NewsletterSignup({ compact = false }: { compact?: boolean }) {
  const [email, setEmail] = useState("");
  const subscribe = trpc.newsletter.subscribe.useMutation({ onSuccess: () => { setEmail(""); toast.success("You’re on the list"); } });
  return <section className={`${compact ? "rounded-2xl border border-[#d7e8eb] bg-[#f8ffff] p-6" : "rounded-[2rem] bg-[#172039] p-7 text-white md:p-10"}`}><div className="flex items-start gap-4"><div className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-xl ${compact ? "bg-[#e9f7f6] text-[#13b8b0]" : "bg-[#c7f76d] text-[#172039]"}`}><Mail size={20} /></div><div><p className={`font-mono text-[10px] uppercase tracking-[.18em] ${compact ? "text-[#13b8b0]" : "text-[#c7f76d]"}`}>The builder dispatch</p><h2 className="mt-2 font-display text-2xl font-semibold tracking-[-.05em]">Useful ideas, not inbox noise.</h2><p className={`mt-2 max-w-xl text-sm leading-6 ${compact ? "text-[#53617d]" : "text-white/70"}`}>Get one practical note when a new Blog article ships. Unsubscribe whenever you want.</p></div></div><form className="mt-6 flex flex-col gap-3 sm:flex-row" onSubmit={event => { event.preventDefault(); subscribe.mutate({ email, source: compact ? "storefront" : "journal" }); }}><label className="sr-only" htmlFor={`newsletter-email-${compact ? "compact" : "wide"}`}>Email address</label><input id={`newsletter-email-${compact ? "compact" : "wide"}`} required type="email" value={email} onChange={event => setEmail(event.target.value)} placeholder="you@example.com" className={`min-w-0 flex-1 rounded-full border px-5 py-3.5 text-sm outline-none ${compact ? "border-[#d7e8eb] bg-white text-[#172039] focus:border-[#13b8b0]" : "border-white/15 bg-white/10 text-white placeholder:text-white/45 focus:border-[#c7f76d]"}`} /><button type="submit" disabled={subscribe.isPending} className={`inline-flex items-center justify-center rounded-full px-5 py-3.5 text-sm font-semibold disabled:opacity-50 ${compact ? "bg-[#172039] text-white hover:bg-[#13b8b0]" : "bg-[#c7f76d] text-[#172039] hover:bg-white"}`}>{subscribe.isPending ? "Joining…" : "Join the list"}<ArrowRight size={16} className="ml-2" /></button></form>{subscribe.isSuccess && <p className={`mt-3 inline-flex items-center gap-2 text-xs ${compact ? "text-[#527f1e]" : "text-[#c7f76d]"}`}><CheckCircle2 size={14} /> You’re subscribed for future dispatches.</p>}</section>;
}
