import { ImagePlus, Loader2, X } from "lucide-react";
import { useRef, useState } from "react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

function readAsDataUrl(file: File) { return new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(new Error("Could not read image")); reader.readAsDataURL(file); }); }

export default function ProductImageDropzone({ value, onChange }: { value: string[]; onChange: (urls: string[]) => void }) {
  const inputRef = useRef<HTMLInputElement>(null); const [dragging, setDragging] = useState(false); const upload = trpc.admin.uploadProductImage.useMutation();
  async function addFiles(files: FileList | File[]) { const chosen = Array.from(files).filter(file => file.type.startsWith("image/") && file.size <= 8_000_000).slice(0, 8 - value.length); if (!chosen.length) { toast.error("Choose image files under 8 MB"); return; } try { const urls = await Promise.all(chosen.map(async file => (await upload.mutateAsync({ dataUrl: await readAsDataUrl(file) })).url)); onChange([...value, ...urls]); toast.success(`${urls.length} image${urls.length === 1 ? "" : "s"} uploaded`); } catch (error) { toast.error(error instanceof Error ? error.message : "Image upload failed"); } }
  return <div className="md:col-span-2"><div onDragEnter={event => { event.preventDefault(); setDragging(true); }} onDragOver={event => event.preventDefault()} onDragLeave={() => setDragging(false)} onDrop={event => { event.preventDefault(); setDragging(false); void addFiles(event.dataTransfer.files); }} onClick={() => inputRef.current?.click()} className={`cursor-pointer rounded-2xl border-2 border-dashed p-5 transition ${dragging ? "border-[#13b8b0] bg-[#dff8f7]" : "border-[#b9d6db] bg-[#f8ffff] hover:border-[#13b8b0]"}`}><input ref={inputRef} type="file" accept="image/*" multiple className="sr-only" onChange={event => { if (event.target.files) void addFiles(event.target.files); event.currentTarget.value = ""; }} /><div className="flex items-center gap-3"><ImagePlus className="text-[#13b8b0]" size={22} /><div><p className="text-sm font-semibold">Drop product images here</p><p className="mt-1 text-xs text-[#71809f]">Up to 8 images · PNG, JPG, WEBP · 8 MB each {upload.isPending ? "· Uploading…" : ""}</p></div>{upload.isPending && <Loader2 className="ml-auto animate-spin text-[#13b8b0]" size={17} />}</div></div>{value.length > 0 && <div className="mt-3 grid grid-cols-4 gap-3 sm:grid-cols-8">{value.map((url, index) => <div key={`${url}-${index}`} className="group relative aspect-square overflow-hidden rounded-xl border border-[#d7e8eb] bg-white"><img src={url} alt={`Product preview ${index + 1}`} className="h-full w-full object-cover" /><button type="button" onClick={event => { event.stopPropagation(); onChange(value.filter((_, itemIndex) => itemIndex !== index)); }} className="absolute right-1 top-1 rounded-full bg-[#172039]/85 p-1 text-white opacity-0 transition group-hover:opacity-100" aria-label={`Remove image ${index + 1}`}><X size={12} /></button>{index === 0 && <span className="absolute bottom-1 left-1 rounded-full bg-[#c7f76d] px-1.5 py-0.5 font-mono text-[8px] uppercase tracking-[.1em]">Cover</span>}</div>)}</div>}</div>;
}
