import { Check, EyeOff, MessageSquareText, Send, Star } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

type ReviewRow = { review: { id: number; rating: number; review: string; isApproved: boolean; adminReply: string | null; createdAt: Date }; buyerName: string | null; buyerEmail: string | null; productTitle: string };
function ReviewCard({ item, onRefresh }: { item: ReviewRow; onRefresh: () => void }) {
  const [reply, setReply] = useState(item.review.adminReply ?? "");
  const moderate = trpc.admin.setReviewApproval.useMutation({ onSuccess: onRefresh, onError: error => toast.error(error.message) });
  const saveReply = trpc.admin.setReviewReply.useMutation({ onSuccess: () => { toast.success(reply.trim() ? "Reply published" : "Reply removed"); onRefresh(); }, onError: error => toast.error(error.message) });
  return <article className={`rounded-2xl border p-5 ${item.review.isApproved ? "border-[#d7e8eb] bg-[#f8ffff]" : "border-[#f1d3ca] bg-[#fff8f5]"}`}><div className="flex flex-col gap-4 md:flex-row md:items-start"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="font-semibold">{item.buyerName ?? item.buyerEmail ?? "Buyer"}</span><span className="rounded-full bg-[#e9f7f6] px-2.5 py-1 font-mono text-[9px] uppercase tracking-[.12em] text-[#53617d]">{item.review.isApproved ? "Published" : "Hidden"}</span></div><p className="mt-2 text-xs text-[#71809f]">{item.productTitle} · {new Date(item.review.createdAt).toLocaleDateString("en-IN")}</p><div className="mt-3 flex items-center gap-1 text-[#d49b00]">{[1, 2, 3, 4, 5].map(star => <Star key={star} size={15} fill={star <= item.review.rating ? "currentColor" : "none"} />)}</div><p className="mt-3 leading-7 text-[#53617d]">{item.review.review}</p>{item.review.adminReply && <div className="mt-4 rounded-xl border-l-4 border-[#13b8b0] bg-[#e9f7f6] p-4"><p className="font-mono text-[9px] uppercase tracking-[.14em] text-[#13b8b0]">Public admin reply</p><p className="mt-2 text-sm leading-6 text-[#53617d]">{item.review.adminReply}</p></div>}<div className="mt-5 rounded-xl bg-[#eef8fa] p-4"><label className="font-mono text-[9px] uppercase tracking-[.14em] text-[#71809f]">Reply publicly</label><textarea value={reply} maxLength={1200} onChange={event => setReply(event.target.value)} placeholder="Thank the buyer or clarify how the product works…" className="mt-2 min-h-20 w-full rounded-lg border border-[#d7e8eb] bg-[#f8ffff] px-3 py-2 text-sm outline-none focus:border-[#13b8b0]" /><div className="mt-2 flex items-center justify-between gap-3"><span className="text-[10px] text-[#71809f]">{reply.length}/1200</span><button type="button" disabled={saveReply.isPending} onClick={() => saveReply.mutate({ id: item.review.id, reply })} className="inline-flex items-center gap-2 rounded-full bg-[#13b8b0] px-4 py-2 text-xs font-semibold text-white disabled:opacity-50"><Send size={13} />{saveReply.isPending ? "Saving…" : reply.trim() ? "Publish reply" : "Remove reply"}</button></div></div></div><button type="button" disabled={moderate.isPending} onClick={() => moderate.mutate({ id: item.review.id, isApproved: !item.review.isApproved })} className={`inline-flex shrink-0 items-center justify-center gap-2 rounded-full px-4 py-2.5 text-sm font-semibold disabled:opacity-50 ${item.review.isApproved ? "border border-[#f1d3ca] text-[#a33e23] hover:bg-[#ffe0d7]" : "bg-[#c7f76d] text-[#172039] hover:bg-[#b7eb57]"}`}>{item.review.isApproved ? <><EyeOff size={15} /> Hide</> : <><Check size={15} /> Publish</>}</button></div></article>;
}
export default function ReviewModerationPanel() { const reviews = trpc.admin.reviews.useQuery(); return <section className="mt-9 space-y-4"><div className="flex items-end justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[.16em] text-[#13b8b0]">Trust & safety</p><h2 className="mt-2 font-display text-3xl font-semibold tracking-[-.06em]">Review moderation</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[#53617d]">Keep buyer feedback useful, honest, and safe. Reply beneath verified reviews or hide content that needs moderation.</p></div><MessageSquareText className="hidden text-[#13b8b0] sm:block" size={28} /></div><div className="space-y-3">{reviews.data?.length ? reviews.data.map(item => <ReviewCard key={item.review.id} item={item as ReviewRow} onRefresh={() => void reviews.refetch()} />) : <div className="rounded-2xl border border-dashed border-[#b9d6db] p-14 text-center"><MessageSquareText className="mx-auto text-[#13b8b0]" size={34} /><h3 className="mt-4 font-display text-2xl font-semibold">No reviews yet.</h3><p className="mt-2 text-sm text-[#53617d]">Verified buyer feedback will appear here.</p></div>}</div></section>; }
